### PR TITLE
Fix `apt does not have a stable CLI interface` warning

### PR DESCRIPTION
**Pull request by JackPGreen**
When doing [a build](https://github.com/hazelcast/hazelcast-packaging/actions/runs/10328301478/job/28594672466), a warning is displayed:
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Migrates `apt` -> `apt-get` to address this.

[Further reading](https://askubuntu.com/a/990838).

### CODE REVIEW

**Comment by nishaatr** [comment]
Just saw this

`sudo apt-get update && sudo apt-get install ${{ env.HZ_DISTRIBUTION}}=${HZ_VERSION}`

Add space after HZ_DISTRIBUTION  `${{ env.HZ_DISTRIBUTION }}`

**Comment by JackPGreen** [comment]
> Just saw this
> 
> `sudo apt-get update && sudo apt-get install ${{ env.HZ_DISTRIBUTION}}=${HZ_VERSION}`
> 
> Add space after HZ_DISTRIBUTION `${{ env.HZ_DISTRIBUTION }}`

Thats existing functionality? I'm guessing it's requesting a specific version of the depedency.

**Comment by nishaatr** [comment]
> > Just saw this
> > `sudo apt-get update && sudo apt-get install ${{ env.HZ_DISTRIBUTION}}=${HZ_VERSION}`
> > Add space after HZ_DISTRIBUTION `${{ env.HZ_DISTRIBUTION }}`
> 
> Thats existing functionality? I'm guessing it's requesting a specific version of the depedency.

In GH I always see surrounding spaces added when referencing variables 
So I am saying might as well correct and add space `${{ env.HZ_DISTRIBUTION}}` --> `${{ env.HZ_DISTRIBUTION }}`

**Comment by JackPGreen** [comment]
> > > Just saw this
> > > `sudo apt-get update && sudo apt-get install ${{ env.HZ_DISTRIBUTION}}=${HZ_VERSION}`
> > > Add space after HZ_DISTRIBUTION `${{ env.HZ_DISTRIBUTION }}`
> > 
> > 
> > Thats existing functionality? I'm guessing it's requesting a specific version of the depedency.
> 
> In GH I always see surrounding spaces added when referencing variables So I am saying might as well correct and add space `${{ env.HZ_DISTRIBUTION}}` --> `${{ env.HZ_DISTRIBUTION }}`

Oh I see what you mean.

I'll fix here as it's trivial, but it's the same in lots of places.

f14d43530f43eae995b079e477121dd64fe186fc

**Pull request merged**
