### PR TITLE
Remove all DEVEL references [DI-241][5.5.z]

### PR DESCRIPTION
**Pull request by nishaatr**
Backport [224](https://github.com/hazelcast/hazelcast-packaging/pull/224)

### CODE REVIEW

**Review by JackPGreen — COMMENTED** [review]
Do we actually need to backport this? Whats the effect of not doing so?

**Comment by nishaatr** [comment]
> Do we actually need to backport this? Whats the effect of not doing so?

Good question. Thought of this and I think no effect if not backported as normally DEVEL is always built from master. 
But thought I do it because:
1. To keep branches  in sync
2. less noise
3. less questions in the future
4. wanted to remove all DEVEL remnants

**Comment by JackPGreen** [comment]
> I think no effect if not backported as normally DEVEL is always built from master

On that basis I think we shouldn't backport.

> But thought I do it because

FYI there is a [backporting policy](https://hazelcast.atlassian.net/wiki/spaces/EN/pages/4066541585/Pull+Request+Porting+Policy).

> To keep branches  in sync

I don't think we should aim to keep the branches in sync - or at least, if we want that there are better ways to do it.
I.E. at the moment we branch these repos _per product release_, but if we want a consistent pipeline for any release it's probably better that `master` just supports all maintenance branches instead and has it's own lifecycle.

**Comment by nishaatr** [comment]
> > I think no effect if not backported as normally DEVEL is always built from master
> 
> On that basis I think we shouldn't backport.
> 
> > But thought I do it because
> 
> FYI there is a [backporting policy](https://hazelcast.atlassian.net/wiki/spaces/EN/pages/4066541585/Pull+Request+Porting+Policy).
> 
> > To keep branches  in sync
> 
> I don't think we should aim to keep the branches in sync - or at least, if we want that there are better ways to do it. I.E. at the moment we branch these repos _per product release_, but if we want a consistent pipeline for any release it's probably better that `master` just supports all maintenance branches instead and has it's own lifecycle.

I am not fussed tbh but prefer to merge for completeness. Also, when looking at README.md in branches and release tag, it would appear as if we support DEVEL. But again not a major concern.

@ldziedziul what do you think?

**Comment by ldziedziul** [comment]
> Do we actually need to backport this? Whats the effect of not doing so?

Taking into account that DEVEL is released only from master, I would say that the most important argument for these backports is to reduce risk of the conflicts and to avoid confusion

>  if we want a consistent pipeline for any release it's probably better that master just supports all maintenance branches instead and has it's own lifecycle.

True, but this is a different topic

I have no strong opinion _slightly_ leaning towards skipping these backports

**Comment by JackPGreen** [comment]
> If still not sure then lets have a quick discuss during Mondays Standup!

👍

**Review by ldziedziul — APPROVED** [review]

**Review by JackPGreen — APPROVED** [review]

**Pull request merged**
